version: '3.3'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-public-certificates:/certificates
    command:
      # Enable Docker in Traefik
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode=false
      - --providers.docker.network=traefik-public
      # Enable the access log
      - --accesslog
      # Enable the Traefik log
      - --log.level=INFO
      # Enable the Dashboard and API
      - --api
      - --api.insecure=false
      - --api.dashboard=true
      # Configure LetsEncrypt resolver
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Global HTTP -> HTTPS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      # HTTP
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME}:${HASHED_PASSWORD}
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-dashboard-http.entrypoints=web
      - traefik.http.routers.traefik-dashboard-http.middlewares=admin-auth
      - traefik.http.services.traefik-dashboard-http.loadbalancer.server.port=8080
      # HTTPS
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-dashboard-https.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard-https.service=api@internal

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
